# Generated by Django 5.2 on 2025-04-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_club_logo_remove_userprofile_clubs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clubs',
            field=models.ManyToManyField(blank=True, related_name='members', to='dashboard.club'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='No bio provided'),
        ),
    ]
